### ISSUE TITLE
The tracking consent popup appears on all servers, even in single player mode

### ISSUE THREAD

**Issue by Parker1200** [rdntcntrl/ratoa_gamecode#28]
It would be nice if there was a way to opt out of the tracking consent popup even with ui_trackConsentConfigured set to 0. Only Ratmod servers that actually use ratstats should display the popup.

**Comment by rdntcntrl** [comment]
The popup that appears after connecting to a server should only appear if the "First Connect" screen was somehow skipped (the stats consent option is also asked there). This usually happens when you join from regular OA and download the mod from the server. 

I don't like the idea of making the server ask for it, since that will give the impression that it is a per-server setting, when it actually applies to all servers.

However, it would be nice if it did not appear for local (single-player) games. Maybe we can specifically detect that?
