### ISSUE TITLE
What is the difference between CrouchSlide and CrouchSlide with SlideMode?

### ISSUE THREAD

**Issue by taysta** [rdntcntrl/ratoa_gamecode#39]
Hi, awesome project, just wondering what this option changes for the crouch sliding, thanks :)

**Comment by oitzujoey** [comment]
`g_crouchSlide 1` enables crouch slide.
`g_slideMode` sets the type of slide.
`g_slideMode 0`: "Conservative" slide
`g_slideMode 1`: "Liberal" slide

Liberal slide has a lot of acceleration for a short period of time, and then starts decelerating. You can only accelerate when turning. Because of the acceleration there is a 600 u/s cap after which no more speed can be gained while sliding. Liberal slide seems to be the faster of the two in practice.
Conservative slide reduces your speed when turning. You can slide forever. Conservative slide works well for positioning for jumps.

**Comment by taysta** [comment]
Thanks for the explanation! 

Which of the two options would be closer to q4 physics in practice? 

And is the 600 speed the maximum speed gained during the slide, or is it a hard cap at 600ups where you gain no further accel beyond that point?

**Comment by rdntcntrl** [comment]
I'm not sure how exactly crouch slide worked in q4 (if it was possible to accelerate or not).
Personally I find slidemode 0 feels more natural (the caps/timeouts in mode 1 are not very intuitive IMHO).

> And is the 600 speed the maximum speed gained during the slide, or is it a hard cap at 600ups where you gain no further accel beyond that point?

I think it's a hard cap.

**Comment by oitzujoey** [comment]
I don't know how Q4 slide works either. I'd guess mode 0 is closer.

600 is the maximum speed you can gain during the slide (aside from rounding error). Once you jump off the ground you can strafe jump to higher than 600.
